import { useState } from 'react';
import type { NextPage } from 'next';
import cx from 'clsx';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { generateSessionId, isSessionId } from './components/Pianuo/utils';
import { Pianuo } from './components/Pianuo';
import { Knob } from './components/Knob';

const Home: NextPage = () => {
  const [ id, setId ] = useState(generateSessionId());

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          head
        </h1> */}

        <div className='.flex-col'>
          <input
            className='mb-10'
            onChange={e => {
              if (isSessionId(e.target.value)) setId(e.target.value);
            }}
          />
          <Knob />
          <Pianuo id={id} />
        </div>
      </main>

      {/* <footer className={styles.footer} /> */}
    </div>
  )
}

export default Home
