import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Pianuo } from './components/Pianuo'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          head
        </h1> */}

        <div className={styles.grid}>
          <Pianuo />
        </div>
      </main>

      <footer className={styles.footer}>
        feet
      </footer>
    </div>
  )
}

export default Home
